### ISSUE TITLE
Add note section to users page [2h, time spent: 1h]

### ISSUE THREAD

**Issue by Marilakeus** [Naisten-Linja/naisten-linja-services#100]
We should be able to have a small note section per every user at the user page that staff could edit.
![Näyttökuva 2022-8-11 kello 14 53 06](https://user-images.githubusercontent.com/104415662/184127581-78ed7fef-c7bf-492c-bf8a-ee7d2afd504b.png)

**Comment by andri-yta** [comment]
This task is linked to #29
