### ISSUE TITLE
Add possibility to edit and delete received online letter

### ISSUE THREAD

**Issue by Marilakeus** [Naisten-Linja/naisten-linja-services#101]
Staff should be able to delete and edit each online letter on vapaaehtoiset.naistenlinja.fi

**Comment by andri-yta** [comment]
@Marilakeus Can you please clarify what the purpose of deleting and editing the letter content is?

Should the staff be able to see the original content after they make an edit to the content?

**Comment by Marilakeus** [comment]
Hey! It would be important to be able to edit online letters, because sometimes they include sensitive information (such as customer name, email etc.)  and we should be able to delete this information before assigning the letter to volunteers. In addition we should be able to delete the letters because according to ethical guidelines, it is not recommended to store letters in our own system for too long.

**Comment by andri-yta** [comment]
The staff members do not need to know the original content.
