### ISSUE TITLE
Integrate online letter service to Sendgrid 

### ISSUE THREAD

**Issue by Marilakeus** [Naisten-Linja/naisten-linja-services#103]
We would need to be able to send message to customer when we have replied to their online letter. They should leave their contact info when sending the letter. Is it possible to store the contact information in a safe place, the staff does not need to know it?

**Comment by andri-yta** [comment]
Based on the meeting, we would have the customers to provide their email addresses voluntarily if they want to receive a notification email whenever the reply has been published. However, we would need to have a GDPR Compliance Statement to state how we process the personal data. It would also allow the customers to have the right to have their personal data erased. This could be done by allowing them to delete it by themselves or requesting for deletion.

Furthermore, the current implementation of publishing the reply would need code changes. There should be a separation between editing for publishing and editing for making a correction. The process would look like as follows:
-  unpublish → edit → publish → a notification email will be sent
-  modify → save → a notification email will **not** be sent
