### ISSUE TITLE
Implement "My account" page where you can change your contact details (email and phone number) if necessary [15hr]

### ISSUE THREAD

**Issue by nathandao** [Naisten-Linja/naisten-linja-services#11]
Since we are already using SSO login via Discourse, it would make sense to have the user updating their contact details there, and we would need to figure out a way to keep the information in sync better between Discourse and the online platform.

Currently, the user information is only updated each time the user login.

One idea for implementation is since the volunteer's information is only accessible by staff user, whose access rights are mapped to Discourse's staff user's group. It's possible to fetch the volunteer's account information straight from the Discourse API if the staff user is already logged in.

**Comment by Marilakeus** [comment]
Is this still open? Volunteers can already edit their contact details and add multi-factor identification on ryhmat.naistenlinja.fi.

**Comment by nathandao** [comment]
Oh true. We can close this one! : )
