### ISSUE TITLE
Add start date and end date to booking types [15h]

### ISSUE THREAD

**Issue by Tiinakoo** [Naisten-Linja/naisten-linja-services#26]
Atm. weekdays can be selected when adding a new booking type, but start date and end date are not defined.

**Comment by nathandao** [comment]
This requires:
- Adding new components to the frontend UI to select start and end date
- Modify the database schema
- Update the bookings API to only show slots that are between the start and end date.

**Comment by Marilakeus** [comment]
We would need this feature in order to create slots for events such as counsellor sessions which happen every now and then.
