### ISSUE TITLE
Add "Read" status for a letter [2h, time spent: 5h]

### ISSUE THREAD

**Issue by nathandao** [Naisten-Linja/naisten-linja-services#30]
Set the letter's status to read when a sender tries to open the letter after it's been responded.

**Comment by andri-yta** [comment]
@Marilakeus do you just want to know whether the customer has opened the reply OR/AND the time when the customer opens the reply for the first time?

Based on the meeting, both will be captured. The read status will be shown under the _Letters_ page and individual reply page.
