### ISSUE TITLE
Add a feedback field for each online letter [4h, time spent: 7h]

### ISSUE THREAD

**Issue by nathandao** [Naisten-Linja/naisten-linja-services#31]
Once the letter has been responded, add a feedback text field to ask for the sender's response.

Will need to clarify if a plain text field would work, or would it be a list of checkbox questions for example?

If it is a text response, make sure it is encrypted the same way as the letter content

**Comment by Marilakeus** [comment]
We need a feedback form that will be displayed to the user at the end of the response to the online letter. We should be able to edit the questions ourselves (in Contentful)? The feedback form should include one or two short questions "Was the reply helpful to you?" etc. and then an open question.

**Comment by Marilakeus** [comment]
Is it possible to integrate some free of charge service customer happiness questionnaire service here?

**Comment by andri-yta** [comment]
Based on the meeting, we will check further on Google Forms.
