### ISSUE TITLE
When staff makes a booking for another user: add a search feature etc. so that finding the user is easier. [1h, time spent: 2h]

### ISSUE THREAD

**Issue by Marilakeus** [Naisten-Linja/naisten-linja-services#65]
We could use a searchable select component instead of just a select dropdown in the reserve a slot view.

![image](https://user-images.githubusercontent.com/6004147/174788069-32ce01d5-8b29-46e6-a611-27146baaa3c1.png)

**Comment by andri-yta** [comment]
For any searchable dropdown, we use a different dropdown library that has more feature. Also, we found an issue with the initial value for full name and email if the login user is already booked. Now it's fixed.
