### ISSUE TITLE
Fix "ajankohtaista" page so that every blog post would have a different url 

### ISSUE THREAD

**Issue by Marilakeus** [Naisten-Linja/naisten-linja-services#71]

**Comment by nathandao** [comment]
This can be done by editing Contentful content. This can be done by creating new pages, and a Content Box Group with links to all sub pages, then add the same Content Box Group to each page.

No code change is needed : )

**Comment by Marilakeus** [comment]
Is there a way to be able to share articles from "ajankohtaista" page with different urls and headlines?

**Comment by andri-yta** [comment]
Additionally, the blog page will have a card view.
![image](https://user-images.githubusercontent.com/106080142/186179396-92b2c298-4f18-4726-9ea0-92ca97fa6611.png)
