### ISSUE TITLE
Allow specifying in Heroku configuration how many days before booking starts the volunteers get a reminder email [1h, time spent: 1h]

### ISSUE THREAD

**Issue by tuomas-tk** [Naisten-Linja/naisten-linja-services#82]
Currently the emails are always sent 3 days before the booking.

Add a new config variable that allows to set the number of days in Heroku.

**Comment by Marilakeus** [comment]
I think we had some kind of misunderstanding here. Volunteers don't need to edit this themselves. Perhaps later we could integrate Sendgrid to this so that I could edit the time, but let's get back to this when all the 1. priority tasks are done.

**Comment by tuomas-tk** [comment]
Oh thank you for the correction @Marilakeus . The easiest way to implement this is to add the configuration option to Heroku config variable section. Should take around an hour to implement, fixed the description now.

**Comment by Marilakeus** [comment]
Great, thanks! Let's get back to this after we have finished with all the 1.priority tasks
