### ISSUE TITLE
Add sorting options for the table [4h, time spent: 2h+1h]

### ISSUE THREAD

**Issue by andri-yta** [Naisten-Linja/naisten-linja-services#85]
This estimation is based on this picture:
![image](https://user-images.githubusercontent.com/106080142/183360847-c7c26a2a-2df2-4608-a216-82fd87b608aa.png)
The sorting options include sorting the full name, last booking, and upcoming booking.

**Comment by tuomas-tk** [comment]
Resolved in #104
