### ISSUE TITLE
Add “my page” to volunteers.naistenlinja.fi [5h]

### ISSUE THREAD

**Issue by Marilakeus** [Naisten-Linja/naisten-linja-services#95]
We need a feedback form that will be displayed to the user at the end of the response to the online letter. We should be able to edit the questions ourselves (in Contentful)? The feedback form should include one or two short questions "Was the reply helpful to you?" etc. and then an open question.

**Comment by Marilakeus** [comment]
Add new page called "My page" to vapaaehtoiset.naistenlinja.fi. The headline could be a link to https://ryhmat.naistenlinja.fi/u/username/preferences/account so that we don't need the create a separate page in order to change passwords etc.

**Comment by andri-yta** [comment]
Since we don't collect the discourse's username, we need to make an update to the database to make the link works.
