### ISSUE TITLE
Add links to letter replies [6h, time spent: 4h]

### ISSUE THREAD

**Issue by Marilakeus** [Naisten-Linja/naisten-linja-services#96]
Our customers should be able to click on the links in online letters.

**Comment by andri-yta** [comment]
W̶e̶ ̶a̶r̶e̶ ̶g̶o̶i̶n̶g̶ ̶t̶o̶ ̶u̶s̶e̶ ̶t̶h̶e̶ ̶m̶a̶r̶k̶d̶o̶w̶n̶ ̶e̶d̶i̶t̶o̶r̶ ̶(̶s̶i̶m̶i̶l̶a̶r̶ ̶t̶o̶ ̶t̶h̶e̶ ̶f̶r̶o̶n̶t̶/̶m̶a̶t̶e̶r̶i̶a̶l̶s̶ ̶p̶a̶g̶e̶)̶ ̶i̶n̶s̶t̶e̶a̶d̶ ̶o̶f̶ ̶t̶h̶e̶ ̶c̶u̶r̶r̶e̶n̶t̶ ̶r̶e̶g̶u̶l̶a̶r̶ ̶t̶e̶x̶t̶b̶o̶x̶.̶
(Edited for clarity)

Solution: use the markdown editor to render the reply content, no need to change the textbox that is currently used for writing the letter/reply.

@Marilakeus does this sound good?

**Comment by Marilakeus** [comment]
I am not sure what do you mean. I mean if we now add a link to our letter reply, it shows as a text not a link

**Comment by andri-yta** [comment]
@Marilakeus Sorry for being unclear. We meant that we will use the same technology like the front-page to make the link clickable. This is how it will look like:
<img width="1192" alt="Screenshot 2022-08-12 at 16 58 23" src="https://user-images.githubusercontent.com/106080142/184369150-74ef4cd0-161d-4411-ae9c-89d3043bd192.png">

So, the link will be clickable if it has www or/and http/https in the front of the address.

**Comment by Marilakeus** [comment]
Okey great, looks good!
