### ISSUE TITLE
Add possibility to edit Google search title and description per url in Contentful [5h, time spent: 4h]

### ISSUE THREAD

**Issue by Marilakeus** [Naisten-Linja/naisten-linja-services#97]
We should be able to edit the Google title and description of each page in Contentful, so that they don't come automatically from the website.

**Comment by andri-yta** [comment]
We are going to create a seo field for Google description in the Contentful, and we also need to make a modification to the public-site code.

**Comment by Marilakeus** [comment]
Also now when we share our website to our social media platforms, the picture is always from the front page despite of which page we actually share. It there something we could do to prevent this?

**Comment by Marilakeus** [comment]
![image (1)](https://user-images.githubusercontent.com/104415662/184353454-553aed8f-018f-4160-b118-f32e1494d3ec.png)
