### ISSUE TITLE
Fix issue related to emails from ryhmat.naistenlinja.fi 

### ISSUE THREAD

**Issue by Marilakeus** [Naisten-Linja/naisten-linja-services#99]
Some of our volunteers don’t receive an invitation email from ryhmat.naistenlinja.fi. These people have work emails such as fimnet.fi. Is there something we can do about it? Would it be possible to add a volunteer account without them receiving a confirmation email?

**Comment by andri-yta** [comment]
We will try to solve the email problems that were logged under SendGrid, but we'll see if it will improve the delivery.

@Marilakeus Do you know if they have checked the Spam folder for the email?

**Comment by Marilakeus** [comment]
Thanks! They have checked the spam folder

**Comment by Marilakeus** [comment]
I also noticed that some people with gmail addresses don't receive our booking confirmation and reminder mails and it shows this message: _The IP address sending this message does not have a PTR record setup, or the corresponding forward DNS entry does not point to the sending IP. As a policy, Gmail does not accept messages from IPs with missing PTR records. Please visit https://support.google.com/mail/answer/81126#ip-practices for more information. e23-20020a811e17000000b0032a133eafb7si11862420ywe.252 - gsmtp_
